### ISSUE TITLE
Broken links to file-format on front page

### ISSUE THREAD

**Issue by petterreinholdtsen** [exponential-decay/the-format-registry#4]
Visiting http://the-fr.org/, there is a link to http://the-fr.org/id/file-format/8 on the front page.  This link do not work, and only give this error: "No results... potentially invalid uri: /data-response-handler.php".  Tested with https instead of http, but same error.

**Comment by ross-spencer** [comment]
Hi there, thanks for the report! It seems something has gone awry with all the format redirects which is a bit of a shame. I tried to revert my PHP version but it didn't work. I haven't a dev environment to debug this at present, but will try and set one up asap. An alternative is to use the SPARQL endpoint, a describe query is shown here: Describe [Query](http://the-fr.org/public/sparql/endpoint.php?query=describe+%3Chttp%3A%2F%2Fthe-fr.org%2Fid%2Ffile-format%2F8%3E&output=tsv&jsonp=&key=&show_inline=1)

**Comment by ross-spencer** [comment]
Hi @petterreinholdtsen, sorry for the inconvenience caused - the site is now mostly fixed now. My hosting installed a new web server with caching. The first impact with this was a slight difference to how we needed to interact with `.htaccess`. The second was some form of caching: https://krystal.co.uk/guides/getting-started/how-to-disable-litespeed-caching which i think is still impacting `fmt/8` - the best way to interact with that for now is via `doc` or data links: http://the-fr.org/doc/file-format/8 - but I'll keep an eye on it and hope it resolves itself in the next few days. 

Thanks for showing an interest in the service. 

I've also updated to PRONOM v94 so all the records are up to date for the information the site uses.

**Comment by petterreinholdtsen** [comment]
[Ross Spencer]
> Thanks for showing an interest in the service.

Thank you very much for looking into this.  Via your list I even found a
way to link to the official site for each format, and is now using it in
<URL: https://gitlab.com/petterreinholdtsen/m701-noark5-katalog/blob/master/formatlist.rst >.

> I've also updated to PRONOM v94 so all the records are up to date for
> the information the site uses.

Very good. :)

-- 
Happy hacking
Petter reinholdtsen

**Comment by ross-spencer** [comment]
That's great @petterreinholdtsen. And a nice looking project. I'm always excited to see more folk using PRONOM's work.
